In [ ]:
#Question 2: Analyze the performance of kNN with respect to accuracy, recall, precision, FPR, and ROC metrics obtained for heart dataset.
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, roc_auc_score
from sklearn import metrics

# dropping target variable and spliting it
df = pd.read_csv("/content/sample_data/heart - heart.csv")
predictors =df.drop('target', axis= 1)  # Use all features excluding target
target = df["target"]
X_train, X_test, y_train, y_test= train_test_split(predictors, target, test_size= 0.20, random_state= 0)


knn= KNeighborsClassifier(n_neighbors=5, n_jobs= -1).fit(X_train, Y_train)
y_pred= knn.predict(X_test)
print("The accuracy is " + str(metrics.accuracy_score(y_test, y_pred) * 100) + "%")
print(f'the confusion matrix is {confusion_matrix(y_test, y_pred)}')
target_names = ["class 0", "class 1"]
print(f'the classification report is:')
print(classification_report(y_test, y_pred, target_names=target_names))
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=1 )
print(f'the False positive rate (FPR) is {fpr}')
print(f'the True positive rate (TPR) is {tpr}')
roc_auc = roc_auc_score(y_test, y_pred)
print(f'the Area under the ROC Curve is {roc_auc}')



The accuracy is 63.934426229508205%
the confusion matrix is [[17 10]
 [12 22]]
the classification report is:
              precision    recall  f1-score   support

     class 0       0.59      0.63      0.61        27
     class 1       0.69      0.65      0.67        34

    accuracy                           0.64        61
   macro avg       0.64      0.64      0.64        61
weighted avg       0.64      0.64      0.64        61

the False positive rate (FPR) is [0.         0.37037037 1.        ]
the True positive rate (TPR) is [0.         0.64705882 1.        ]
the Area under the ROC Curve is 0.6383442265795207


In [ ]:
#Question 3: Test the kNN algorithm with k=3, 6, 8, and 9 on heart dataset. Study the impact on performance metrics.

k = [3, 6,8, 9]
for i in k:
  print("FOR K= "+ str(i))
  knn= KNeighborsClassifier(n_neighbors=i, n_jobs= -1).fit(X_train, Y_train)
  Y_pred= knn.predict(X_test)
  print("The accuracy is "+str(metrics.accuracy_score(Y_test,Y_pred)*100)+"%")
  print(confusion_matrix(Y_test, Y_pred))
  target_names = ['class 0', 'class 1']
  print(classification_report(Y_test, Y_pred,target_names=target_names))



FOR K= 3
The accuracy is 63.934426229508205%
[[17 10]
 [12 22]]
              precision    recall  f1-score   support

     class 0       0.59      0.63      0.61        27
     class 1       0.69      0.65      0.67        34

    accuracy                           0.64        61
   macro avg       0.64      0.64      0.64        61
weighted avg       0.64      0.64      0.64        61

FOR K= 6
The accuracy is 65.57377049180327%
[[18  9]
 [12 22]]
              precision    recall  f1-score   support

     class 0       0.60      0.67      0.63        27
     class 1       0.71      0.65      0.68        34

    accuracy                           0.66        61
   macro avg       0.65      0.66      0.65        61
weighted avg       0.66      0.66      0.66        61

FOR K= 8
The accuracy is 68.85245901639344%
[[19  8]
 [11 23]]
              precision    recall  f1-score   support

     class 0       0.63      0.70      0.67        27
     class 1       0.74      0.68      0.71    

In [ ]:
# Question 4: Test the kNN algorithm with Euclidean and Manhattan distance metrics on heart dataset. Study the impact on performance metrics.

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from collections import Counter


# Features and target
X = df.drop('target', axis=1).values
y = df['target'].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Distance functions
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b)**2))

def manhattan_distance(a, b):
    return np.sum(np.abs(a - b))

# KNN prediction function
def knn_predict(X_train, y_train, X_test, k, distance_metric):
    predictions = []
    for x_test in X_test:
        distances = []
        for x_train, y_train_label in zip(X_train, y_train):
            if distance_metric == 'euclidean':
                dist = euclidean_distance(x_test, x_train)
            elif distance_metric == 'manhattan':
                dist = manhattan_distance(x_test, x_train)
            distances.append((dist, y_train_label))

        # Sort by distance and get the k nearest neighbors
        distances.sort(key=lambda x: x[0])
        k_nearest_neighbors = [label for _, label in distances[:k]]

        # Get the most common class label among the k nearest neighbors
        most_common = Counter(k_nearest_neighbors).most_common(1)
        predictions.append(most_common[0][0])

    return np.array(predictions)

# Set the value of k
k = 3

# Predict using Euclidean distance
y_pred_euclidean = knn_predict(X_train, y_train, X_test, k, 'euclidean')

# Predict using Manhattan distance
y_pred_manhattan = knn_predict(X_train, y_train, X_test, k, 'manhattan')

# Confusion matrix and classification report for Euclidean distance
print("Euclidean Distance:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_euclidean))
print("Classification Report:")
print(classification_report(y_test, y_pred_euclidean))

# Confusion matrix and classification report for Manhattan distance
print("Manhattan Distance:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_manhattan))
print("Classification Report:")
print(classification_report(y_test, y_pred_manhattan))


Euclidean Distance:
Confusion Matrix:
[[17 10]
 [12 22]]
Classification Report:
              precision    recall  f1-score   support

           0       0.59      0.63      0.61        27
           1       0.69      0.65      0.67        34

    accuracy                           0.64        61
   macro avg       0.64      0.64      0.64        61
weighted avg       0.64      0.64      0.64        61

Manhattan Distance:
Confusion Matrix:
[[16 11]
 [10 24]]
Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.59      0.60        27
           1       0.69      0.71      0.70        34

    accuracy                           0.66        61
   macro avg       0.65      0.65      0.65        61
weighted avg       0.65      0.66      0.65        61



In [ ]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, roc_auc_score
from sklearn import metrics

df2= pd.read_csv("/content/sample_data/spambase.csv")
predictors2= df2.drop('spam', axis= 1)
target2= df2['spam']
X_train, X_test, y_train, y_test= train_test_split(predictors2, target2, test_size= 0.20, random_state= 0)
knn= KNeighborsClassifier(n_neighbors=5, n_jobs= -1).fit(X_train, y_train)
y_pred= knn.predict(X_test)
print("The accuracy is " + str(metrics.accuracy_score(y_test, y_pred) * 100) + "%")
print(f'the confusion matrix is {confusion_matrix(y_test, y_pred)}')
target_names = ["class 0", "class 1"]
print(f'the classification report is:')
print(classification_report(y_test, y_pred, target_names=target_names))
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=1 )
print(f'the False positive rate (FPR) is {fpr}')
print(f'the True positive rate (TPR) is {tpr}')
roc_auc = roc_auc_score(y_test, y_pred)
print(f'the Area under the ROC Curve is {roc_auc}')

The accuracy is 80.56460369163952%
the confusion matrix is [[463  75]
 [104 279]]
the classification report is:
              precision    recall  f1-score   support

     class 0       0.82      0.86      0.84       538
     class 1       0.79      0.73      0.76       383

    accuracy                           0.81       921
   macro avg       0.80      0.79      0.80       921
weighted avg       0.80      0.81      0.80       921

the False positive rate (FPR) is [0.        0.1394052 1.       ]
the True positive rate (TPR) is [0.         0.72845953 1.        ]
the Area under the ROC Curve is 0.7945271627825714
