In [ ]:
import numpy as np

In [ ]:
# Question 1
# bold elements; 9 and 12, 5 and 4
data1= np.array([1 ,3 ,9 ,12, 18])
data2=np.array([[1,5,2,0], [3,6, 4,7]])
data3= np.array([['7','6'], ['5', '4'],['3', '2']])
data4= np.array([[11, 52, 20, 50],[34, 61, 43, 17]])

print(data1)
print(data2)
print(data3)
print(data4)

[ 1  3  9 12 18]
[[1 5 2 0]
 [3 6 4 7]]
[['7' '6']
 ['5' '4']
 ['3' '2']]
[[11 52 20 50]
 [34 61 43 17]]


In [ ]:
#Question 3: Add Data1 in Data1. Multiply Data1 by 10. Convert Data1, Data2, Data3, and Data4 datatypes to integer.

answer1 = data1 + data1
print(answer1)
answer1 = answer1 * 10
print(answer1)

data1= data1.astype(int)
data2= data2.astype(int)
data3= data3.astype(int)
data4= data4.astype(int)

[ 2  6 18 24 36]
[ 20  60 180 240 360]


In [ ]:
# Question 4: Create a 3x5 array of 0s. 2x8 array of 1s, 6x3 array of integer random numbers.

data5= np.zeros((3,5))
data6= np.ones((6,3))
data7= np.random.normal(size= (6,3))

print(data5)
print(data6)
print(data7)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[-1.16753361  1.15585971 -0.9504492 ]
 [-0.56894703 -0.38411838 -1.19645127]
 [ 0.96454548 -0.06931939  0.37769789]
 [-1.05006888  1.00348579  0.60127037]
 [ 0.52472748  0.24148155  0.37847678]
 [-1.50759821 -0.63227178  0.24023949]]


In [ ]:
# Question 5: Square the bold elements of Data1 and Data2. Hint: use indexing and slicing.

answer2= data1[2:4]
answer3= data2[[0, 1], [1, 2]]

print(answer2**2)
print(answer3**2)

[ 81 144]
[25 16]


In [ ]:
# Question 6: Consider an array Subjects =ML OS CCN OS AI MP CCN ML AI. Set all courses to 0 except ML and AI. Hint: use Boolean indexing.

data8= np.array([['ML', 'OS', 'CCN'], ['OS', 'AI', 'MP'], ['CCN', 'ML', 'AI']])
answer4= np.logical_or(data8 == 'ML', data8 == 'AI')
data8[~answer4] = 0
data8

array([['ML', '0', '0'],
       ['0', 'AI', '0'],
       ['0', 'ML', 'AI']], dtype='<U3')

In [ ]:
#Question 7: Transpose the Data2, Data3, and Data4 arrays using appropriate function.

answer5= np.transpose(data2)

answer6= np.transpose(data3)

answer7= np.transpose(data4)
print(answer5)
print(answer6)
print(answer7)

[[1 3]
 [5 6]
 [2 4]
 [0 7]]
[[7 5 3]
 [6 4 2]]
[[11 34]
 [52 61]
 [20 43]
 [50 17]]


In [ ]:
#Question 8: Concatenate Data2 and Data4 using vstack and hstack.

answer8= np.hstack((data2, data4))
print(answer8)

answer9= np.vstack((data2, data4))
print(answer9)

[[ 1  5  2  0 11 52 20 50]
 [ 3  6  4  7 34 61 43 17]]


<function print>

In [ ]:
# Question 9: Demean each column of Data2. Hint: use broadcasting.

mean2= data2.mean(axis= 0)

data2_demean= data2 - mean2
print(data2)
print(mean2)
data2_demean

[[1 5 2 0]
 [3 6 4 7]]
[2.  5.5 3.  3.5]


array([[-1. , -0.5, -1. , -3.5],
       [ 1. ,  0.5,  1. ,  3.5]])

In [ ]:
# Question 10: Convert Data2 shape into 4x2. Hint: Use reshape function.

answer10= data2.reshape(4,2)

print(answer10)

[[1 5]
 [2 0]
 [3 6]
 [4 7]]


In [ ]:
#Question 11: Consider the table having marks of three students scored in three subjects. Compute the maximum score of each subject. Hint: use max function.

data9= np.array([[60, 70, 50],
        [40, 60, 80],
        [70, 55, 65]])


answer11= list(data9.max(axis= 1))
print(answer11)
for index, value in enumerate(answer11, start= 1):
  print("Max marks of Subject"+ str(index) + " is: " + str(value))


[70, 80, 70]
Max marks of Subject1 is: 70
Max marks of Subject2 is: 80
Max marks of Subject3 is: 70


In [ ]:
#Question 12: Compute the CGPA of all three students using the following formula and tables 1.11 and 1.12 (Hint:Use ufunc methods).
data9_subject_student= np.array([
        [60, 70, 50],
        [40, 60, 80],
        [70, 55, 65]])
hours= np.array([[2],
                 [3],
                 [4]])
# # print(hours.shape)
# # print(data9_subject_student.shape)
# total_hours= hours.sum()
# print(total_hours)

# hours_point= np.multiply( hours, data9_subject_student)
# hours_point_sum= hours_point.sum(axis= 0)
# print(hours_point)
# print(hours_point_sum)


# cgpa= np.divide(hours_point_sum, total_hours)
# cgpa= cgpa.astype('int32')
# cgpa= list(cgpa)
# print(cgpa)
# # for index, value in enumerate(cgpa, start= 1):
# #   print("Student" + str(index) +  " is " + str(value))

# for index, value in enumerate(cgpa, start= 1):
#   if value >= 57 and value <= 59:
#     print("The grade is C-" + " of the Student " + str(index))
#   elif value >= 60 and value <= 63:
#     print("The grade is C" + " of the Student " + str(index))
#   elif value >= 64 and value <= 66:
#     print("The grade is C+" + " of the Student " + str(index))
#   elif value >= 67 and value <= 69:
#     print("The grade is B-" + " of the Student " + str(index))
data9_new_row = []  # Initialize an empty list to store rows of grades

for data_row in data9_subject_student:
    data9_new = []  # Initialize a new list for each row
    for data in data_row:
        if data < 50:
            grade = 0.0
        elif 50 <= data <= 53:
            grade = 1.0
        elif 54 <= data <= 56:
            grade = 1.4
        elif 57 <= data <= 59:
            grade = 1.7
        elif 60 <= data <= 63:
            grade = 2.0
        elif 64 <= data <= 66:
            grade = 2.4
        elif 67 <= data <= 69:
            grade = 2.7
        elif 70 <= data <= 74:
            grade = 3.0
        elif 75 <= data <= 79:
            grade = 3.4
        elif 80 <= data <= 84:
            grade = 3.7
        elif 85 <= data <= 93:
            grade = 4.0
        elif 94 <= data <= 100:
            grade = 4.0
        data9_new.append(grade)  # Append the grade to the current row
    data9_new_row.append(data9_new)  # Append the completed row to the final result

data9_new_row  # This will be the new array with grading points
data9_new_row= np.array(data9_new_row)
print(data9_new_row)
hours_point= np.multiply( hours, data9_new_row)
print(hours_point)
sum_hours_point= np.sum(hours_point, axis= 0)
print(sum_hours_point)
total_hours= hours.sum()
cgpa= np.divide(sum_hours_point, total_hours)
cgpa

[[2.  3.  1. ]
 [0.  2.  3.7]
 [3.  1.4 2.4]]
[[ 4.   6.   2. ]
 [ 0.   6.  11.1]
 [12.   5.6  9.6]]
[16.  17.6 22.7]


array([1.77777778, 1.95555556, 2.52222222])

In [ ]:
#Question 13: Compute the sorted unique values in subjects array.

data8= np.array([['ML', 'OS', 'CCN'], ['OS', 'AI', 'MP'], ['CCN', 'ML', 'AI']])

data9_sort= np.sort(data8)

answer12= np.unique(data9_sort)

print(answer12)

['AI' 'CCN' 'ML' 'MP' 'OS']


In [ ]:
# Question 14: Compute the dot product and inverse of 4x4 random matrix. Hint: Use numpy.linalg functions.

data10= np.random.normal(size= (4,4))
data10

answer12= np.linalg.inv(data10)
answer12
answer13= np.dot(data10, answer12)
print(answer13)

[[ 1.00000000e+00 -1.44948716e-16 -1.82659133e-16  5.31333868e-17]
 [-2.45692548e-16  1.00000000e+00 -1.01943473e-16  5.54657768e-17]
 [-7.41855079e-16  5.11119003e-16  1.00000000e+00 -3.92285368e-17]
 [ 2.05440941e-16  1.39312493e-16  8.25758635e-17  1.00000000e+00]]


In [ ]:
#Question 15: Store all the created arrays on disk.


# np.savez('lab1_arrays.npz', data1= data1, data2= data2, data3= data3, data4=data4)

# from google.colab import drive

# drive.mount("/content/drive")

arr = np.loadtxt('/content/drive/MyDrive/Colab Notebook For ML Excercise/lab1_arrays.txt', delimiter=',')
arr



FileNotFoundError: /content/drive/MyDrive/Colab Notebook For ML Excercise/lab1_arrays.txt not found.